apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: idp-beflydemo
  description: Demonstration For Be-Fly
  annotations:
    github.com/project-slug: darede-labs/idp-beflydemo
spec:
  type: service
  lifecycle: experimental
  owner: group:default/matheus.andrade@darede.com.br
