apiVersion: platform.darede.io/v1alpha1
kind: Aurora
metadata:
  name: beflydemo-db
  namespace: beflydemo
  labels:
    db.engine: aurora-postgresql
  annotations:
    platform.darede.io/provisioningRunId: "21fbd4bf-642c-41c0-8737-d99cc1033b5b"
spec:
  compositionSelector:
    matchLabels:
      db.engine: aurora-postgresql
  appName: beflydemo
  dbSize: M  # S | M | L
  dbEngine: aurora-postgresql  # aurora-postgresql | aurora-mysql | postgresql | mysql
  engineVersion: "17.9"
  

  # VPC Configuration (auto-populated from platform-params ConfigMap)
  vpcId: "vpc-0b050e119ea97ff04"

  # Private subnet IDs for Aurora subnet group (must be in different AZs)
  # Auto-populated from EKS cluster VPC configuration
  subnetIds:
    ["subnet-0c9e3902a62022850","subnet-045e94472e0068db7","subnet-0086df67ce197c14d"]

  # Security group that will be allowed to connect to Aurora on port 5432
  # Using EKS node security group for direct pod-to-DB connectivity
  allowedSecurityGroupId: "sg-06e8c156b7703c26b"

  # Master password secret reference (must exist before creating Aurora)
  masterPasswordSecretRef:
    name: beflydemo-aurora-master-password
    namespace: beflydemo
    key: password

  # Write connection secret directly to the app namespace
  # Keys: username, password, endpoint, port, database
  writeConnectionSecretToRef:
    name: beflydemo-db-conn
