apiVersion: platform.darede.io/v1alpha1
kind: StaticWebsite
metadata:
  name: beflydemo-web
  namespace: beflydemo
  annotations:
    platform.darede.io/provisioningRunId: "21fbd4bf-642c-41c0-8737-d99cc1033b5b"
spec:
  siteName: beflydemo
  region: us-east-1
  indexDocument: index.html
  errorDocument: index.html
  priceClass: PriceClass_100
  backendOriginDomain: internal-beflydemo.timedevops.click
  customDomain: beflydemo.timedevops.click
  acmCertificateArn: arn:aws:acm:us-east-1:948881762705:certificate/051f6515-0d0b-459c-a056-0663f7c88f5e
  hostedZoneId: Z09212782MXWNY5EYNICO
