apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: beflydemo-backend
  namespace: argocd
  labels:
    platform.darede.io/app: "beflydemo"
    platform.darede.io/component: "backend"
  annotations:
    argocd.argoproj.io/sync-wave: "10"
    platform.darede.io/provisioningRunId: "21fbd4bf-642c-41c0-8737-d99cc1033b5b"
spec:
  project: apps
  source:
    repoURL: https://github.com/darede-labs/idp-beflydemo.git
    targetRevision: main
    path: infra
    directory:
      include: '{deployment.yaml,service.yaml,ingress.yaml}'
  destination:
    server: https://kubernetes.default.svc
    namespace: beflydemo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
